### ISSUE TITLE
upgrade gralde wrapper

### ISSUE THREAD

**Issue by robstoll** [robstoll/tutteli-gradle-plugins#16]
TODO:
- update the gradle wrapper
- rename the resulting `gradlew` back to `gr`/`gr.bat`

**Comment by jGleitz** [comment]
Updating to Gradle Wrapper 6.0.1 breakes the kotlin plugin for versions lower than ~1.3.50. This means we would need to remove the tests that explicitly test against older versions of the kotlin plugin (I think the publish plugin is the only one having that).

Shall we still upgrade (I’m in favour)?

**Comment by robstoll** [comment]
Fine with me
