### ISSUE TITLE
validateBeforePublish is too agressive: it requires GPG_PASSPHRASE even for generatePomFileForJvmPublication

### ISSUE THREAD

**Issue by vlsi** [robstoll/tutteli-gradle-plugins#215]
1. Clone Atrium
2. `cd translations/atrium-translations-de_CH`
3. `../../gradlew generatePomFileForJvmPublication`

```
> Task :atrium-translations-de_CH:validateBeforePublish FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':atrium-translations-de_CH:validateBeforePublish'.
> You need to define property with name gpgPassphrase or System.env variable with name GPG_PASSPHRASE for publishing (empty or blank is considered to be undefined)
```

I don't see why I need a GPG_PASSPHRASE for generating a pom file.

**Comment by robstoll** [comment]
99% of the time I only generate poms during a release. for the other 1% I skip verification and signing. would it be enough, if you can specify `tutteliPublish.sign = false ` (maybe that even works already)

**Comment by vlsi** [comment]
I do not understand why generating poms requires signing. I generate pom to double-check if they are in a good shape.
Of course, I can add `-x validateBeforePublish`, however, it is really weird that validation fails the build when nobody asked for the validation in the first place.

If you really need a validation, then you could configure the set of validations based on the taskGraph: `project.gradle.taskGraph.whenReady`, so you can check which tasks are there and adjust accordingly.

For me, 0% of the cases includes publishing Atrium, so I bump into excessive validation in 100% of the cases.

**Comment by robstoll** [comment]
> For me, 0% of the cases includes publishing Atrium,
That was expected :laughing: 

I totally get your point and I only want to find out what exactly we need to change
I assume you also don't want validation and signing when you do a publicationXyToMavenLocal, right?

**Comment by vlsi** [comment]
I was running exactly `gradlew generatePomFileForJvmPublication` and other `generatePom` tasks.

I do not care about `publicationXyToMavenLocal`, and I can understand that publication to MavenLocal would require PGP signing.

**Comment by robstoll** [comment]
OK, going to change it accordingly

**Comment by robstoll** [comment]
I'll move all other checks such as is a groupId set, is a version set etc. into the ValidationTask and let it only run when a publish occurs.
