### ISSUE TITLE
Remove ch.tutteli.junitjacoco 

### ISSUE THREAD

**Issue by jGleitz** [robstoll/tutteli-gradle-plugins#23]
As far as I can see, the plugin serves no purpose anymore. The JUnit Platform Plugin is deprecated and all settings the plugin applies can can easliy be done through gradle or the jacoco plugin.

Or is there any reason to keep this plugin?

**Comment by robstoll** [comment]
I use it in multiple projects and use it to share the configuration. Does it bother you?

**Comment by jGleitz** [comment]
I am trying to update this plugin such that it uses no deprecated features anymore (with the goal that atrium’s build doesn’t use any deprecated features anymore).

There are two courses of action: Adapt the junitjacoco plugin such that its behaviour does not change, or remove it entirely because it does not do that much anymore.

I would personally go with the second option because even though it is more work now, it means one less thing to maintain. But I also do not know how often this plugin is used.

**Comment by jGleitz** [comment]
For reference: I estimate that removing `ch.tutteli.junitjacoco` would require adding 1-6 lines to the gradle configuration of projects using it (mainly adding the jacoco plugin instead of this one, enabling junitPlatform, setting up report types)

**Comment by robstoll** [comment]
The change now is of course easy, copying the configuration to about 4 projects. I have this plugin more for maintenance reasons. I don't want to fix 4 projects next time there is deprecated functionality.

**Comment by jGleitz** [comment]
Okay. So you prefer keeping it?

**Comment by robstoll** [comment]
I tend to yes but what change is required?

**Comment by jGleitz** [comment]
The plugin dependes on the junit-platform plugin, which has now been deprecated for a long time. It also does not support IDE reporting and such.

**Comment by robstoll** [comment]
Nah... that was already fixed by you, no?

**Comment by jGleitz** [comment]
Whoa, yes. What the hell.

**Comment by robstoll** [comment]
closing it then
