### ISSUE TITLE
Module Info Plugin breaks with Kotlin 1.3.40

### ISSUE THREAD

**Issue by jGleitz** [robstoll/tutteli-gradle-plugins#26]
With Kotlin 1.3.40 or later, the module info plugin will no longer cause build failures if the `module-info.java` is missing entries for dependencies.

To reproduce: 

1. Checkout [`jGleitze:update-gradle`](https://github.com/jGleitz/tutteli-gradle-plugins/tree/update-gradle)
2. Change [ModuleInfoPluginIntTest#KOTLIN_VERSION](https://github.com/jGleitz/tutteli-gradle-plugins/blob/update-gradle/tutteli-gradle-kotlin-module-info/src/test/groovy/ch/tutteli/gradle/kotlin/module/info/ModuleInfoPluginIntTest.groovy#L17) to be `1.3.61` (or any other Kotlin version that is at least `1.3.40`)
3. See how `ModuleInfoPluginIntTest` fails for the cases where the build should break
4. Spends hours changing the configuration without fixing the issue

**Comment by robstoll** [comment]
I don't understand your 4. point, you spent a lot of hours without finding a fix or what do you mean?

**Comment by jGleitz** [comment]
Yes, I did. The fourth point was intended to be houmerous, but seemingly failed at that 😀

**Comment by robstoll** [comment]
Sorry, I am apparently a bad joke reader :grimacing:
I don't have time to look into it right now. Does it block you?

**Comment by jGleitz** [comment]
It does not block me, but will become an issue when we upgrade atrium’s gradle version (https://github.com/robstoll/atrium-roadmap/issues/51)

**Comment by robstoll** [comment]
good, I'll probably have time on Friday otherwise next week

**Comment by robstoll** [comment]
Unfortunately a kotlin bug :( https://youtrack.jetbrains.com/issue/KT-36105
I'll have to work around it

**Comment by robstoll** [comment]
Looks like the problem is fixed in Kotlin 1.5.21 :tada:
